# Data / mixing
img_size: 224
total_batch_size: 256
# nffa_fraction: 0.5
num_workers: 8

# MoCo
proj_dim: 128
hidden_dim: 2048
queue_size: 65536
momentum: 0.999
temperature: 0.07

# Train
epochs: 200
lr: 0.03
weight_decay: 0.0001
momentum_sgd: 0.9
use_amp: true
# val_fraction: 0.05  # Fraction of data used for validation
eval_every_epochs: 1  # Evaluate every N epochs

# Saving
save_every_epochs: 5
seed: 42

# Debug paths
train_dir: ./datasets/train_stage2
eval_dir: ./datasets/eval_stage2
out_dir: ./checkpoints/moco_stage2
log_dir: ./logs/moco_stage2
