# Paths
train_dir: /datasets/sem_moco/train_stage_2
eval_dir: /datasets/sem_moco/eval_stage_2
out_dir: ./checkpoints/stage2
log_dir: ./logs/stage2

# Train
epochs: 250

# WandB
wandb_project: sem_moco_stage2
