# Paths
train_dir: /datasets/sem_moco/train_stage_1
eval_dir: /datasets/sem_moco/eval_stage_1
out_dir: ./checkpoints/stage1
log_dir: ./logs/stage1

# Train
epochs: 250

# WandB
wandb_project: sem_moco_stage1
